spring:
  application:
    name: vacation-service
  output:
    ansi:
      enabled: always
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}-${spring.application.instance_id:${random.value}}
